version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongodb

networks:
  compose-bridge:
    # A bridge network uses a software bridge which allows containers connected to the same bridge network to communicate,
    # while providing isolation from containers which are not connected to that bridge network.
    driver: bridge
